set -o vi

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval "$(ssh-agent -s)"
    /usr/bin/ssh-add -K ~/.ssh/beauknowssoftware_rsa
fi

if [ -f /usr/local/share/bash-completion/bash_completion ]; then
    . /usr/local/share/bash-completion/bash_completion
fi

if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi
