#!/usr/bin/env bash

function md() {
  mkdir -p "$@" && cd "$@"
}

function cd() {
    command cd "$@"
    ll
}

function awsCreds() {
    function _awsCredsSet() {
        if [ -z "$1" ]; then
            echo "Missing profile"
            echo $"Usage: awsCreds set [profile]"
        else
            export AWS_PROFILE="$1"
        fi
    }

    function _awsCredsDetails() {
        aws configure list
    }

    function _awsCredsCurrent() {
        echo "$AWS_PROFILE"
    }

    function _awsCredsList() {
        less ~/.aws/credentials | grep -E "\[.*\]" | sed s/"\[\(.*\)\]"/\\1/g
    }

    function _awsCredsPick() {
        profiles=($(_awsCredsList))
        select profile in "${profiles[@]}"; do
            _awsCredsSet "$profile"
            break
        done
    }

    case "$1" in
        s|set)
            _awsCredsSet "$2"
            ;;
        l|list)
            _awsCredsList 
            ;;
        c|current)
            _awsCredsCurrent
            ;;
        d|details)
            _awsCredsDetails
            ;;
        p|pick)
            _awsCredsPick
            ;;
        *)
            echo $"Usage: awsCreds {set|list|current|details|pick}"
            return 1
            ;;
    esac
}

function aws_account_info {
  [ "$AWS_ACCOUNT_NAME" ] && [ "$AWS_ACCOUNT_ROLE" ] && echo "aws:($AWS_ACCOUNT_NAME:$AWS_ACCOUNT_ROLE) "
}

function getAWSSession {
    set -e

    clearAWSSession

    mfa="$1"

    if [ -z "$mfa" ]; then
        echo -n "mfa: "
        read -s mfa
    fi

    serialNumber=$(aws sts get-caller-identity --output text --query "Arn" | sed "s/user/mfa/g")
    session=($(aws sts get-session-token --serial-number "$serialNumber" --token-code "$mfa" --query "[Credentials.SecretAccessKey,Credentials.SessionToken,Credentials.AccessKeyId]" --output text))
    export AWS_SECRET_ACCESS_KEY=${session[0]}
    export AWS_SESSION_TOKEN=${session[1]}
    export AWS_ACCESS_KEY_ID=${session[2]}

    set +e
}

function clearAWSSession {
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN
    unset AWS_ACCESS_KEY_ID
}

if [ -f ~/.bash_functions.local ]; then
    source ~/.bash_functions.local
fi
