alias ..="cd .."
alias cd..="cd .."

alias where=which # sometimes i forget

colorflag="-G"

export CLICOLOR_FORCE=1

# ls options: F = put `/` after folders, h = byte unit suffixes
alias ls='ls -Fh ${colorflag}'

# List all files colorized in long format, including dot files
alias la="ls -lhA ${colorflag}"
alias ll='la'

# File size
alias fs="stat -f \"%z bytes\""

alias reload="source ~/.bash_profile  && echo 'Shell config reloaded from ~/.bash_profile'"

alias cls='clear'

alias path='echo -e ${PATH//:/\\n}'

alias now='date +"%T"'

alias +x='chmod +x'

alias git=hub

if [ -f ~/.bash_aliases.local ]; then
  . ~/.bash_aliases.local
fi
